'''
	Autor : Marco Jhoel Churata Torres
	Fecha : 04 - 06 - 2020
	Nombre : Inventario_venta_UI.py
	Descripcion : Este es el codigo de la parte grafica.Gracias
'''

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\inventario_farmacia.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VENTANA(object):
    def setupUi(self, VENTANA):
        VENTANA.setObjectName("VENTANA")
        VENTANA.setEnabled(True)
        VENTANA.resize(793, 651)
        font = QtGui.QFont()
        font.setPointSize(9)
        VENTANA.setFont(font)
        self.centralwidget = QtWidgets.QWidget(VENTANA)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 45, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 40, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 40, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 40, 61, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(550, 50, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(650, 50, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.nom_pro = QtWidgets.QLineEdit(self.centralwidget)
        self.nom_pro.setGeometry(QtCore.QRect(180, 70, 151, 21))
        self.nom_pro.setReadOnly(True)
        self.nom_pro.setObjectName("nom_pro")
        self.Lab = QtWidgets.QLineEdit(self.centralwidget)
        self.Lab.setGeometry(QtCore.QRect(340, 70, 113, 21))
        self.Lab.setReadOnly(True)
        self.Lab.setObjectName("Lab")
        self.p_unit = QtWidgets.QLineEdit(self.centralwidget)
        self.p_unit.setGeometry(QtCore.QRect(550, 70, 91, 21))
        self.p_unit.setReadOnly(True)
        self.p_unit.setObjectName("p_unit")
        self.monto_t = QtWidgets.QLineEdit(self.centralwidget)
        self.monto_t.setGeometry(QtCore.QRect(650, 70, 113, 21))
        self.monto_t.setReadOnly(True)
        self.monto_t.setObjectName("monto_t")
        self.tabla_int = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_int.setEnabled(True)
        self.tabla_int.setGeometry(QtCore.QRect(10, 100, 761, 192))
        self.tabla_int.setMinimumSize(QtCore.QSize(651, 192))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.tabla_int.setFont(font)
        self.tabla_int.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabla_int.setAutoFillBackground(False)
        self.tabla_int.setAutoScroll(True)
        self.tabla_int.setAutoScrollMargin(16)
        self.tabla_int.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_int.setDragEnabled(False)
        self.tabla_int.setShowGrid(True)
        self.tabla_int.setWordWrap(True)
        self.tabla_int.setCornerButtonEnabled(True)
        self.tabla_int.setObjectName("tabla_int")
        self.tabla_int.setColumnCount(6)
        self.tabla_int.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tabla_int.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.tabla_int.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(9, 5, item)
        self.tabla_int.horizontalHeader().setVisible(True)
        self.tabla_int.horizontalHeader().setCascadingSectionResizes(True)
        self.tabla_int.horizontalHeader().setDefaultSectionSize(124)
        self.tabla_int.horizontalHeader().setHighlightSections(True)
        self.tabla_int.horizontalHeader().setMinimumSectionSize(20)
        self.tabla_int.horizontalHeader().setSortIndicatorShown(False)
        self.tabla_int.horizontalHeader().setStretchLastSection(False)
        self.tabla_int.verticalHeader().setCascadingSectionResizes(False)
        self.tabla_int.verticalHeader().setDefaultSectionSize(25)
        self.tabla_int.verticalHeader().setHighlightSections(True)
        self.tabla_int.verticalHeader().setMinimumSectionSize(100)
        self.tabla_int.verticalHeader().setSortIndicatorShown(False)
        self.boleta = QtWidgets.QTableWidget(self.centralwidget)
        self.boleta.setGeometry(QtCore.QRect(10, 340, 491, 192))
        self.boleta.setObjectName("boleta")
        self.boleta.setColumnCount(5)
        self.boleta.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        item.setText("1")
        self.boleta.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(7, 4, item)
        self.boleta.horizontalHeader().setDefaultSectionSize(100)
        self.boleta.horizontalHeader().setMinimumSectionSize(50)
        self.boleta.verticalHeader().setDefaultSectionSize(25)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 300, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(230, 20, 551, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 30, 20, 71))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 20, 31, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(530, 320, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(530, 350, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(530, 380, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(530, 410, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.bot_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.bot_agregar.setGeometry(QtCore.QRect(100, 60, 71, 31))
        self.bot_agregar.setObjectName("bot_agregar")
        self.cod_bus = QtWidgets.QLineEdit(self.centralwidget)
        self.cod_bus.setGeometry(QtCore.QRect(20, 70, 71, 21))
        self.cod_bus.setAlignment(QtCore.Qt.AlignCenter)
        self.cod_bus.setObjectName("cod_bus")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(530, 440, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(530, 470, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(530, 500, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.fecha = QtWidgets.QLineEdit(self.centralwidget)
        self.fecha.setGeometry(QtCore.QRect(630, 320, 141, 21))
        self.fecha.setAcceptDrops(False)
        self.fecha.setReadOnly(True)
        self.fecha.setObjectName("fecha")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(460, 70, 81, 21))
        self.spinBox.setObjectName("spinBox")
        self.box_doc = QtWidgets.QComboBox(self.centralwidget)
        self.box_doc.setGeometry(QtCore.QRect(630, 350, 141, 21))
        self.box_doc.setObjectName("box_doc")
        self.box_doc.addItem("")
        self.num_doc = QtWidgets.QLineEdit(self.centralwidget)
        self.num_doc.setGeometry(QtCore.QRect(630, 380, 141, 21))
        self.num_doc.setObjectName("num_doc")
        self.vendedor = QtWidgets.QLineEdit(self.centralwidget)
        self.vendedor.setGeometry(QtCore.QRect(630, 440, 141, 21))
        self.vendedor.setObjectName("vendedor")
        self.cliente = QtWidgets.QLineEdit(self.centralwidget)
        self.cliente.setGeometry(QtCore.QRect(630, 470, 141, 21))
        self.cliente.setReadOnly(False)
        self.cliente.setObjectName("cliente")
        self.turno = QtWidgets.QComboBox(self.centralwidget)
        self.turno.setGeometry(QtCore.QRect(630, 500, 141, 21))
        self.turno.setObjectName("turno")
        self.turno.addItem("")
        self.turno.addItem("")
        self.tipo_pago = QtWidgets.QComboBox(self.centralwidget)
        self.tipo_pago.setGeometry(QtCore.QRect(630, 410, 141, 21))
        self.tipo_pago.setObjectName("tipo_pago")
        self.tipo_pago.addItem("")
        self.generar_venta = QtWidgets.QPushButton(self.centralwidget)
        self.generar_venta.setGeometry(QtCore.QRect(530, 530, 241, 31))
        self.generar_venta.setObjectName("generar_venta")
        self.terminar = QtWidgets.QPushButton(self.centralwidget)
        self.terminar.setGeometry(QtCore.QRect(530, 560, 241, 31))
        self.terminar.setObjectName("terminar")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 540, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(100, 540, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(170, 540, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(240, 540, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(330, 540, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(400, 540, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 560, 81, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(100, 560, 61, 21))
        self.lineEdit_11.setReadOnly(False)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(170, 560, 61, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(240, 560, 81, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(330, 560, 61, 21))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.total_general = QtWidgets.QLineEdit(self.centralwidget)
        self.total_general.setGeometry(QtCore.QRect(400, 560, 91, 21))
        self.total_general.setReadOnly(True)
        self.total_general.setObjectName("total_general")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(770, 40, 21, 251))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(160, 300, 621, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(160, 310, 351, 31))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(500, 340, 20, 241))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(10, 600, 771, 21))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(770, 320, 20, 281))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(10, 580, 501, 31))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        VENTANA.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VENTANA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 21))
        self.menubar.setObjectName("menubar")
        VENTANA.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VENTANA)
        self.statusbar.setObjectName("statusbar")
        VENTANA.setStatusBar(self.statusbar)

        self.retranslateUi(VENTANA)
        QtCore.QMetaObject.connectSlotsByName(VENTANA)

    def retranslateUi(self, VENTANA):
        _translate = QtCore.QCoreApplication.translate
        VENTANA.setWindowTitle(_translate("VENTANA", "MainWindow"))
        self.label.setText(_translate("VENTANA", "PRODUCTOS EN VENTA"))
        self.label_2.setText(_translate("VENTANA", "Codigo"))
        self.label_3.setText(_translate("VENTANA", "Nombre Producto"))
        self.label_4.setText(_translate("VENTANA", "Laboratorio"))
        self.label_5.setText(_translate("VENTANA", "Cantidad"))
        self.label_6.setText(_translate("VENTANA", "P.Unitario"))
        self.label_7.setText(_translate("VENTANA", "Monto Total"))
        self.tabla_int.setSortingEnabled(False)
        item = self.tabla_int.verticalHeaderItem(0)
        item.setText(_translate("VENTANA", "1"))
        item = self.tabla_int.verticalHeaderItem(1)
        item.setText(_translate("VENTANA", "2"))
        item = self.tabla_int.verticalHeaderItem(2)
        item.setText(_translate("VENTANA", "3"))
        item = self.tabla_int.verticalHeaderItem(3)
        item.setText(_translate("VENTANA", "4"))
        item = self.tabla_int.verticalHeaderItem(4)
        item.setText(_translate("VENTANA", "5"))
        item = self.tabla_int.verticalHeaderItem(5)
        item.setText(_translate("VENTANA", "6"))
        item = self.tabla_int.verticalHeaderItem(6)
        item.setText(_translate("VENTANA", "7"))
        item = self.tabla_int.verticalHeaderItem(7)
        item.setText(_translate("VENTANA", "8"))
        item = self.tabla_int.verticalHeaderItem(8)
        item.setText(_translate("VENTANA", "9"))
        item = self.tabla_int.verticalHeaderItem(9)
        item.setText(_translate("VENTANA", "10"))
        item = self.tabla_int.horizontalHeaderItem(0)
        item.setText(_translate("VENTANA", "Codigo"))
        item = self.tabla_int.horizontalHeaderItem(1)
        item.setText(_translate("VENTANA", "Nombre Producto                        "))
        item = self.tabla_int.horizontalHeaderItem(2)
        item.setText(_translate("VENTANA", "Laboratorio"))
        item = self.tabla_int.horizontalHeaderItem(3)
        item.setText(_translate("VENTANA", "Cantidad"))
        item = self.tabla_int.horizontalHeaderItem(4)
        item.setText(_translate("VENTANA", "P.Unitario"))
        item = self.tabla_int.horizontalHeaderItem(5)
        item.setText(_translate("VENTANA", "Monto Total"))
        __sortingEnabled = self.tabla_int.isSortingEnabled()
        self.tabla_int.setSortingEnabled(False)
        item = self.tabla_int.item(0, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(0, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(0, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(0, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(0, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(0, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(1, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(1, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(1, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(1, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(1, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(1, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(2, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(2, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(2, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(2, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(2, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(2, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(3, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(3, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(3, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(3, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(3, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(3, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(4, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(4, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(4, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(4, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(4, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(4, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(5, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(5, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(5, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(5, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(5, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(5, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(6, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(6, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(6, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(6, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(6, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(6, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(7, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(7, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(7, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(7, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(7, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(7, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(8, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(8, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(8, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(8, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(8, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(8, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(9, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(9, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(9, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(9, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(9, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(9, 5)
        item.setText(_translate("VENTANA", "-"))
        self.tabla_int.setSortingEnabled(__sortingEnabled)
        item = self.boleta.verticalHeaderItem(1)
        item.setText(_translate("VENTANA", "2"))
        item = self.boleta.verticalHeaderItem(2)
        item.setText(_translate("VENTANA", "3"))
        item = self.boleta.verticalHeaderItem(3)
        item.setText(_translate("VENTANA", "4"))
        item = self.boleta.verticalHeaderItem(4)
        item.setText(_translate("VENTANA", "5"))
        item = self.boleta.verticalHeaderItem(5)
        item.setText(_translate("VENTANA", "6"))
        item = self.boleta.verticalHeaderItem(6)
        item.setText(_translate("VENTANA", "7"))
        item = self.boleta.verticalHeaderItem(7)
        item.setText(_translate("VENTANA", "8"))
        item = self.boleta.horizontalHeaderItem(0)
        item.setText(_translate("VENTANA", "Producto"))
        item = self.boleta.horizontalHeaderItem(1)
        item.setText(_translate("VENTANA", "Cantidad"))
        item = self.boleta.horizontalHeaderItem(2)
        item.setText(_translate("VENTANA", "Unidad"))
        item = self.boleta.horizontalHeaderItem(3)
        item.setText(_translate("VENTANA", "P.Unit"))
        item = self.boleta.horizontalHeaderItem(4)
        item.setText(_translate("VENTANA", "Importe"))
        __sortingEnabled = self.boleta.isSortingEnabled()
        self.boleta.setSortingEnabled(False)
        item = self.boleta.item(0, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(0, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(0, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(0, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(0, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(1, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(1, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(1, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(1, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(1, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(2, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(2, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(2, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(2, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(2, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(3, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(3, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(3, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(3, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(3, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(4, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(4, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(4, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(4, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(4, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(5, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(5, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(5, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(5, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(5, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(6, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(6, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(6, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(6, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(6, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(7, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(7, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(7, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(7, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(7, 4)
        item.setText(_translate("VENTANA", "-"))
        self.boleta.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("VENTANA", "Detalle de Venta"))
        self.label_9.setText(_translate("VENTANA", "FCH.Emision"))
        self.label_10.setText(_translate("VENTANA", "TIP.DOC"))
        self.label_11.setText(_translate("VENTANA", "Nro.DOC"))
        self.label_12.setText(_translate("VENTANA", "Tipo de Pago"))
        self.bot_agregar.setText(_translate("VENTANA", "Agregar ¡¡"))
        self.cod_bus.setText(_translate("VENTANA", "ffff"))
        self.label_13.setText(_translate("VENTANA", "Vendedor"))
        self.label_14.setText(_translate("VENTANA", "Cliente"))
        self.label_15.setText(_translate("VENTANA", "Turno VTA."))
        self.box_doc.setItemText(0, _translate("VENTANA", "DNI"))
        self.turno.setItemText(0, _translate("VENTANA", "MAÑANA"))
        self.turno.setItemText(1, _translate("VENTANA", "TARDE"))
        self.tipo_pago.setItemText(0, _translate("VENTANA", "CONTADO"))
        self.generar_venta.setText(_translate("VENTANA", "Generar VENTA"))
        self.terminar.setText(_translate("VENTANA", "Terminar"))
        self.label_16.setText(_translate("VENTANA", "Valor Venta"))
        self.label_17.setText(_translate("VENTANA", "%Dcto"))
        self.label_18.setText(_translate("VENTANA", "DCTO"))
        self.label_19.setText(_translate("VENTANA", "Sub.Total"))
        self.label_20.setText(_translate("VENTANA", "I.G.V"))
        self.label_21.setText(_translate("VENTANA", "Total General"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VENTANA = QtWidgets.QMainWindow()
    ui = Ui_VENTANA()
    ui.setupUi(VENTANA)
    VENTANA.show()
    sys.exit(app.exec_())

